project:
  type: website
  output-dir: docs # GitHub Pages will serve from /docs

website:
  title: "Caffeine and chaos"
  description: "A collection of my notes, questions and experiment logs."
  favicon: favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Posts
      - about.qmd
    right:
      - icon: github
        href: https://github.com/Ashley936
      - icon: linkedin
        href: https://www.linkedin.com/in/namita-rastogi-453224201/
contents:
  - path: posts/
    drafts: false
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    code-fold: false # keep code visible by default for an ML audience
    code-tools: true
    highlight-style: github

execute:
  freeze: auto # cache execution, don't rerun unchanged code on every render

